/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/annotated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Annotated */
        get: operations["annotated_v1_annotated_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/union": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Union */
        get: operations["union_v1_union_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnnotatedResponse */
        AnnotatedResponse: {
            /** Id */
            id: string;
            /** Passcode */
            passcode: components["schemas"]["OptionalPasscode"] | components["schemas"]["RequiredPasscode"];
        };
        /** OptionalPasscode */
        OptionalPasscode: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            required: "True";
            /** Passcode Length */
            passcode_length: number;
        };
        /** RequiredPasscode */
        RequiredPasscode: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            required: "False";
        };
        /** UnionResponse */
        UnionResponse: {
            /** Id */
            id: string;
            /** Passcode */
            passcode: components["schemas"]["OptionalPasscode"] | components["schemas"]["RequiredPasscode"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    annotated_v1_annotated_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnotatedResponse"];
                };
            };
        };
    };
    union_v1_union_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnionResponse"];
                };
            };
        };
    };
}
