/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Users V1 */
        get: operations["get_users_v1_v1_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** PasscodeNotRequired */
        PasscodeNotRequired: {
            /**
             * Require Passcode
             * @default false
             * @constant
             * @enum {boolean}
             */
            require_passcode: false;
        };
        /** PasscodeRequired */
        PasscodeRequired: {
            /**
             * Require Passcode
             * @default true
             * @constant
             * @enum {boolean}
             */
            require_passcode: true;
            /** Passcode Length */
            passcode_length: number;
        };
        /** V1UserResponseModel */
        V1UserResponseModel: {
            /** Id */
            id: string;
            /** Passcode */
            passcode: components["schemas"]["PasscodeNotRequired"] | components["schemas"]["PasscodeRequired"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    get_users_v1_v1_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V1UserResponseModel"][];
                };
            };
        };
    };
}
